force-app/main/default/objects/Lead/fields/Project_Scope__c.field-meta.xml
<CustomField>
    <fullName>Project_Scope__c</fullName>
    <label>Project Scope</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_Of_Project__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Home Interiors</fullName>
            </value>
            <value>
                <fullName>Home Decor</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bed Room</fullName>
            </value>
            <value>
                <fullName>Hall Interior</fullName>
            </value>
            <value>
                <fullName>Conference Hall</fullName>
            </value>
            <value>
                <fullName>Fully Office Interiors</fullName>
            </value>
            <value>
                <fullName>Office Decor</fullName>
            </value>
            <value>
                <fullName>Office Space</fullName>
            </value>
            <value>
                <fullName>Dining Hall</fullName>
            </value>
            <value>
                <fullName>Cabins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Supervisor_User__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Lead Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Scope__c.field-meta.xml
<CustomField>
    <fullName>Project_Scope__c</fullName>
    <label>Project Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Office Interiors</fullName>
            </value>
            <value>
                <fullName>Home Decor</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Bed Room</fullName>
            </value>
            <value>
                <fullName>Hall Interior</fullName>
            </value>
            <value>
                <fullName>Conference Hall</fullName>
            </value>
            <value>
                <fullName>Office Decor</fullName>
            </value>
            <value>
                <fullName>Office Space</fullName>
            </value>
            <value>
                <fullName>Dining Hall</fullName>
            </value>
            <value>
                <fullName>Cabins</fullName>
            </value>
            <value>
                <fullName>Full Home Interiors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Supervisor_User__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Vendor_Category__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Category__c</fullName>
    <label>Vendor Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Woodwork</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Interior</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Cleaning &amp; Finishing</fullName>
            </value>
            <value>
                <fullName>Material Handling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit_Report__c/Site_Visit_Report__c.object-meta.xml
<CustomObject>
    <label>Site Visit Report</label>
    <nameField>
        <displayFormat>SVR-{0000}</displayFormat>
        <label>Site Visit Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit_Report__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Site Visit Reports</relationshipLabel>
    <relationshipName>Site_Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Site Visit Reports</relationshipLabel>
    <relationshipName>Site_Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit_Report__c/fields/Supervisor_User__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor User</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$UserRole.Name</field>
            <operation>equals</operation>
            <value>Supervisor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit_Report__c/fields/Total_Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Cost__c</fullName>
    <label>Total Estimated Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Site_Visit_Report__c/fields/Wizard_Step__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Step__c</fullName>
    <description>This is for Track last completed step in the site visit report fill component</description>
    <label>Wizard Step</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Category__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Category__c</fullName>
    <label>Vendor Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning &amp; Finishing</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Electrical and Lighting</fullName>
            </value>
            <value>
                <fullName>Woodwork and Furniture</fullName>
            </value>
            <value>
                <fullName>Walls and Paintings</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Ceiling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor_Assignment__c/Vendor_Assignment__c.object-meta.xml
<CustomObject>
    <label>Vendor Assignment</label>
    <nameField>
        <displayFormat>VA-{0000}</displayFormat>
        <label>Vendor Assignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Assignment__c/fields/Supervisor_User__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Supervisor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Assignment__c/fields/Vendor_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select opportunity value to display the vendor opportunities.</errorMessage>
        <filterItems>
            <field>Vendor_Opportunity__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vendor_Opportunity__c</referenceTo>
    <relationshipLabel>Vendor Assignments</relationshipLabel>
    <relationshipName>Vendor_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Opportunity__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quotation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select Quotation relted to the Opportunity.</errorMessage>
        <filterItems>
            <field>Quotation__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Vendor Opportunities</relationshipLabel>
    <relationshipName>Vendor_Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Opportunity__c/fields/Vendor_Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Opportunity_Status__c</fullName>
    <label>Vendor Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Abscond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataUtility.cls
@isTest
public class TestDataUtility {

    // 1. Create User
    public static User createSupervisorUser(String alias) {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        User u = new User(
            Alias = alias, 
            Email = alias + '@testorg.com', 
            EmailEncodingKey = 'UTF-8', 
            LastName = 'Testing', 
            LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey = 'America/Los_Angeles', 
            UserName = alias + DateTime.now().getTime() + '@testorg.com'
        );
        insert u;
        return u;
    }

    // 2. Create Project
    public static Project__c createProject(String name) {
        Project__c proj = new Project__c(
            Name = name, 
            Status__c = 'In Progress'
        );
        insert proj;
        return proj;
    }

    // 3. Create Opportunity
    public static Opportunity createOpportunity(String name, Id supervisorId) {
        Opportunity opp = new Opportunity(
            Name = name,
            StageName = 'Proposal',
            CloseDate = Date.today().addDays(30),
            Supervisor_User__c = supervisorId,
            Project_Scope__c = 'Dining Hall'
        );
        insert opp;
        return opp;
    }

    // 4. Create Vendor
    public static Vendor__c createVendor(String name, String category, String email) {
        Vendor__c vendor = new Vendor__c(
            Name = name,
            Email__c = email,
            Vendor_Category__c = category,
            Vendor_Status__c = 'Available',
            Average_Efficiency__c = 95.5
        );
        insert vendor;
        return vendor;
    }

    // 5. Create File (ContentVersion)
    public static ContentVersion createContentVersion(String title, String fileContent) {
        ContentVersion cv = new ContentVersion(
            Title = title,
            PathOnClient = title + '.pdf',
            VersionData = Blob.valueOf(fileContent),
            IsMajorVersion = true
        );
        insert cv;
        return cv;
    }

    // 6. Link File to Record (ContentDocumentLink)
    public static ContentDocumentLink linkFileToRecord(Id contentVersionId, Id linkedEntityId) {
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionId].ContentDocumentId;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = linkedEntityId,
            ContentDocumentId = conDocId,
            ShareType = 'V'
        );
        insert cdl;
        return cdl;
    }

    // 7. Create Email Templates
    public static void createEmailTemplates() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<EmailTemplate> templates = new List<EmailTemplate>();
            
            templates.add(new EmailTemplate(
                DeveloperName = 'Backup_Tendor_Invitation',
                Name = 'Backup Tender Invitation',
                Subject = 'Tender: {{{project_scope}}}',
                HtmlValue = '<html><body>Test Email Backup {{{Vendor_Category__c}}}</body></html>',
                TemplateType = 'custom',
                FolderId = UserInfo.getUserId()
            ));

            templates.add(new EmailTemplate(
                DeveloperName = 'Quatation_Email_Template',
                Name = 'Quotation Email Template',
                Subject = 'New Tender: {{{project_scope}}}',
                HtmlValue = '<html><body>Test Email New {{{Vendor_Category__c}}}</body></html>',
                TemplateType = 'custom',
                FolderId = UserInfo.getUserId()
            ));
            
            insert templates;
        }
    }

    // ==========================================================================
    // Wrapper class to solve "Excessive Parameter List"
    // ==========================================================================
    public class AbscondDataParams {
        public Id oppId;
        public Id vendorId;
        public Id supervisorId;
        public Id projId;
        public String voStatus;
        public Decimal completion;
        
        // Removed the constructor. We will use property assignment directly.
    }

    // 8. Complex Data: Abscond Data
    public static void createAbscondData(AbscondDataParams params) {
        Vendor_Opportunity__c vo = new Vendor_Opportunity__c(
            Opportunity__c = params.oppId,
            Vendor__c = params.vendorId,
            Vendor_Opportunity_Status__c = params.voStatus
        );
        insert vo;

        Vendor_Assignment__c va = new Vendor_Assignment__c(
            Vendor_Opportunity__c = vo.Id,
            Opportunity__c = params.oppId,
            Supervisor_User__c = params.supervisorId,
            Project__c = params.projId,
            Vendor_Work_Start_Date__c = Date.today(),
            Vendor_Work_End_Date__c = Date.today().addDays(5),
            Completion__c = params.completion
        );
        insert va;

        Task t = new Task(
            Subject = 'Test Task',
            Status = 'Not Started',
            WhatId = va.Id
        );
        insert t;
    }

    // 9. Complex Data: Spec Data
    public static void createSpecData(Id oppId, String category, String productName) {
        Interior_Product__c product = new Interior_Product__c(Name = productName);
        insert product;

        ContentVersion cv = createContentVersion('Spec File ' + productName, 'Test File Content');
        linkFileToRecord(cv.Id, product.Id);

        Project_Specification__c spec = new Project_Specification__c(
            Opportunity__c = oppId,
            Interior_Product__c = product.Id,
            Vendor_Category__c = category
        );
        insert spec;
    }
    // 10. Create Payment Term (Dynamic Parent Linking)
    public static Payment_Term__c createPaymentTerm(Id parentId, String label, Decimal percentage) {
        Payment_Term__c term = new Payment_Term__c(
            Term_Label__c = label,
            Percentage__c = percentage,
            Due_Date__c = Date.today().addDays(15),
            Name = label
        );

        // Dynamically determining parent type
        String sObjName = parentId.getSObjectType().getDescribe().getName();
        if (sObjName == 'Opportunity') {
            term.Opportunity__c = parentId;
        } else if (sObjName == 'Project__c') {
            term.Project__c = parentId;
        }

        insert term;
        return term;
    }
    // 11. Create Lead
    public static Lead createLead(String lastName) {
        Lead l = new Lead(
            LastName = lastName, 
            Company = 'Test Company', 
            Status = 'Open - Not Contacted' // Adjust based on your Org's picklist
        );
        insert l;
        return l;
    }

    // 12. Create Site Visit Report (Handles RecordType Lookup)
    public static Site_Visit_Report__c createSiteVisitReport(Id parentId, String rtName) {
        // Fetch RecordTypeId by Name to match Controller logic
        Id rtId = Schema.SObjectType.Site_Visit_Report__c
            .getRecordTypeInfosByName()
            .get(rtName)
            .getRecordTypeId();

        Site_Visit_Report__c svr = new Site_Visit_Report__c(
            RecordTypeId = rtId,
            Wizard_Step__c = 1,
            Total_Estimated_Cost__c = 1000 // FIXED: Populating required field
        );

        // Dynamic Parent Linking
        String sObj = parentId.getSObjectType().getDescribe().getName();
        if (sObj == 'Lead') {
            svr.Lead__c = parentId;
        } else if (sObj == 'Opportunity') {
            svr.Opportunity__c = parentId;
        }
        
        insert svr;
        return svr;
    }

    // 13. Create Vendor Opportunity (Simple)
    public static Vendor_Opportunity__c createVendorOpportunity(Id oppId, Id vendorId, String status) {
        Vendor_Opportunity__c vo = new Vendor_Opportunity__c(
            Opportunity__c = oppId,
            Vendor__c = vendorId,
            Vendor_Opportunity_Status__c = status
        );
        insert vo;
        return vo;
    }

    // 14. Create Custom Quotation
    public static Quotation__c createQuotation(Id oppId, String name) {
        Quotation__c q = new Quotation__c(
            Name = name, // Standard Name field
            Opportunity__c = oppId 
            // Add other required fields here if you have them (e.g. Status__c)
        );
        insert q;
        return q;
    }
}